### PR TITLE
Changes to FFO and MKS317

### PR DESCRIPTION
**Pull request by ghalym**
ENH: VGC FFO AutoReset
DEV: Modify limit based on experience with EM1K0-GMD-GPI-40

### CODE REVIEW

**Comment by ghalym** [comment]
@slacAWallace I am not sure why every new pull request still show the old commits. Any idea what I could be doing wrong here?

**Comment by slacAWallace** [comment]
Tough to say without knowing your workflow. @klauer or @ZLLentz might have a better idea.

**Comment by klauer** [comment]
Take a look here and see where your master is in comparison to where pcdshub's is: https://github.com/pcdshub/lcls-twincat-vacuum/network

**Comment by ZLLentz** [comment]
All of these "extra" commits are not present on the pcdshub master branch. I assume this is because your pull requests were merged via a squash commit?

You can avoid this in the future by starting from exactly the pcdshub master branch when you make changes.

**Comment by ZLLentz** [comment]
The other thing you can do to help avoid this is to make a new branch instead of working on your own master branch. Then you can keep your master as a mirror of pcdshub/master and then you're always starting from the shared master when you create new branches in the future. There is some elaboration here: https://pcdshub.github.io/development.html

**Review by slacAdpai — APPROVED** [review]
Looks good

**Pull request merged**
