### PR TITLE
Now with Persistent Data

### PR DESCRIPTION
**Pull request by ghalym**
The protection/ interlock setpoints are now copied into persistent variables every time the value is changed. The (non zero) persistent value is copied to the device structure on PLC restarts/downloads.

### CODE REVIEW

**Comment by slacAdpai** [comment]
Have these changes been tested?

**Comment by ghalym** [comment]
@slacAdpai Yes, They have been tested on PLC Proto1 with a test Vacuum project with simulated devices.
Values remain after: Power outage, activate config, reset cold and code download.
NOTE: Values are lost after reset origin. 
So we shouldn't do that.

Non Zero values are copied from the persistent data to the deice structure and when the value is changed from epics it is saved back to the persistent data.

**Comment by slacAdpai** [comment]
That sounds great! Do we still need to restart the ioc after the power outage or will the persistent data do that already? Do the expert screens work properly as well, where the readback value and the value in the ioc match?

**Comment by ghalym** [comment]
The IOC restart was for the Autosave to write the values from the pv to the pv_RBV.
But now we don't have to do that. The _RBV should have the persistent data as written to it by the epics pv.

Now there might be few edge cases where the expert screen won't show the same values. - if the value is changed from the PLC and not epics. - If the value written in EPICS but due to any issue is not actually written to the PLC.

**Review by slacAdpai — APPROVED** [review]

**Comment by jyin999** [comment]
image

Is this a bug in above codes? when need to copy a new setpoint value to persistent variable, should it be like this?
If not (iq_stValve.rAt_VAC_SP = rAT_vac_sp) then
    rAT_vac_sp := iq_stValve.rAt_VAC_SP
END_IF

**Comment by ghalym** [comment]
@jyin999 Which FB is this? I had this problem and fixed it after I tested it.
Can you point me to the fb or the file with this code?

**Comment by jyin999** [comment]
I was looking at VGC function line 471 on this "Now with Persistent Data #75" version.  Which one to review? I though each version are changes related to different functions. I should review all them.  So I started from top. : )

**Pull request merged**
