### PR TITLE
BUG: Mks500EP voltage lower limit removal 

### PR DESCRIPTION
**Pull request by n-wbrown**
Please note the change to L2SIVacuum/POUs/Functions/Gauges/FB_MKS500_EP.TcPOU. 

This addresses the concern that MKS500s are considered to be off when reporting a voltage under .4V. Due to the the MKS500's overloading of the analog output, these values are actually legitimate readings despite being superimposed upon the same range as the HV OFF (0 V) and NO DISCHARGE (.5V) signals that the gauge may send. 

Instead the HV signal, IG.q_xHV_DIS is used to determine if the gauge is off. We should consider using an actual voltage if we alter the Analog Output slope of the gauges to use non-overloaded voltages to signify HV OFF and NO DISCHARGE states.

@slacAWallace 
@ghalym 
@slacAdpai

### CODE REVIEW

**Comment by slacAWallace** [comment]
I think we should maintain the ability for the gauge to tell us that discharge has not started, on all version of the interface.

To do this I recommend changing the following in both the gauge configuration and the fb:
vbase := 1
pbase := 1E-10

This gives ample breathing room between off, starting, and the bottom of the range.

**Comment by ghalym** [comment]
Can we also change the discharge voltage in the configuration to a lower value than 0.5?

I would suggest maybe 0.1V and this will be the limit in the function block too.

**Comment by slacAWallace** [comment]
Just curious, why 0.1V?

**Comment by ghalym** [comment]
So there will be no confusion between a valid pressure value and the no discharge. Its low enough.

**Comment by slacAWallace** [comment]
so vbase = 0.1 and pbase = 1e-10?

**Comment by ghalym** [comment]
vbase is the slope, right? then it should remain 1.

**Comment by slacAWallace** [comment]
Vbase is the lowest point on the voltage curve.

**Comment by slacAWallace** [comment]
Setting configurator to 9.8 - gauge off, 9.3 - gauge is starting, 1V @1E-10, 1V/decade

**Comment by slacAWallace** [comment]
Can this be closed? Or is this a change that still needs to make it in?

**Comment by ghalym** [comment]
This change has the old values from the old configurator.

**Pull request closed without merging**
